### ISSUE TITLE
Missing Header File - catch.hpp

### ISSUE THREAD

**Issue by scottfurry** [cviebig/sql#1]
Checked out code from repository. Went to compile and received numerous error messages that header file `catch.hpp` was missing. Eventually tracked down that problem was associated to an external project: `https://github.com/catchorg/Catch2` (I think...)

Suggest change to project README for others to know they need to grab this and where exactly the header file can be placed in project to be compatible with existing CMakeLists.txt.

**Comment by cviebig** [comment]
Hello Scott,

you are right, this one was missing. I'm sorry. It is fixed now.

Best regards
Christoph
